imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: "@rskaoz4BackendBundle/Resources/config/services.xml" }
    - { resource: "@rskaoz4Bundle/Resources/config/config.yml" }


parameters:
    sonata.user.admin.groupname: Credentials
    sonata.user.admin.user.entity: rs\kaoz4Bundle\Entity\User
    sonata.user.admin.user.class: rs\kaoz4BackendBundle\Admin\UserAdmin

jms_security_extra:
#    secure_controllers:  true
    secure_all_services: false
jms_aop:
    cache_dir: %kernel.cache_dir%/jms_aop            

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        sonata.block.service.text: ~
        sonata.block.service.rss: ~

sonata_admin:
    #security_handler: sonata.admin.security.handler.noop
    title:      Digital.Kaoz.net
    title_logo: /bundles/sonataadmin/logo_title.png
    
fos_user:
    db_driver: orm
    firewall_name: secured_area
    user_class: rs\kaoz4Bundle\Entity\User

#vich_uploader:
#    db_driver: orm
#    mappings:
#        kaoz4_image:
#            upload_dir: %kernel.root_dir%/../web/upload
