#rskaoz4BackendBundle:
#    resource: "@rskaoz4BackendBundle/Controller/"
#    type:     annotation
#    prefix:   /

# Internal routing configuration to handle ESI
_internal:
   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
   prefix:   /_internal

blog_show:
    pattern:   /
    defaults:  { _controller: SonataAdminBundle:Core:dashboard }
    
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    
_sonata_admin:
    resource: .
    type: sonata_admin