language: php

php:
  - 5.3
  - 5.4

env:
  - SYMFONY_VERSION=v2.0.5
  - SYMFONY_VERSION=origin/master

before_script:
  - export TIMETRAP=false
  - php bin/vendors install
  - export TIMETRAP=true
  - app/console
  - cd app

notifications:
  email:
    - seroscho@googlemail.com

