language: php

php:
  - 5.3
  - 5.4

env:
  - SYMFONY_VERSION=v2.1-dev

before_script:
  - cp app/config/parameters.example.yml app/config/parameters.yml
  - php bin/vendors.php
  - sh vendor/elastic/search/bin/elasticsearch

script: "phpunit -c app/"
  
after_script:
  
notifications:
  email:
    - seroscho@googlemail.com

