language: php

php:
  - 5.3
  - 5.4

env:
  - SYMFONY_VERSION=v2.0.5
  - DB=sqlite
#  - SYMFONY_VERSION=origin/master

before_script:
  - cp app/config/parameters.example.yml app/config/parameters.yml
  - bin/vendors install 10 0
  - bin/vendors install 10 10
  - bin/vendors install 10 20
  - bin/vendors install 10 30
  - bin/vendors install 10 40 
  - ln -s ../../../../bootstrap/ ./vendor/bundles/Mopa/BootstrapBundle/Resources/

script: "sh -c 'cd app; phpunit'"
  
after_script:
  
notifications:
  email:
    - seroscho@googlemail.com

