# app/config/config.yml
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata_admin_doctrine_phpcr.tree_block:
#            settings:
#                id: '/cms'
            contexts:   [admin]

cmf_block:
  content_basepath: /cms

sonata_admin:
    templates:
        # default global templates
        ajax:    SonataAdminBundle::ajax_layout.html.twig
    dashboard:
        blocks:
            # display a dashboard block
            - { position: right, type: sonata.admin.block.admin_list }
            - { position: left, type: sonata_admin_doctrine_phpcr.tree_block }
        groups:
            content:
                label: page content
                items:
#                    - cmf_content.multilang.admin
                    - cmf_content.admin
                    - cmf_block.simple_admin
                    - cmf_block.container_admin
                    - cmf_block.reference_admin
                    - cmf_block.action_admin
#                    - cmf_block.string_admin
            routing:
                label: page routes
                items:
                    - cmf_routing.route_admin
                    - cmf_routing.redirect_route_admin
            menu:
                label: menu structure
                items:
                    - cmf_menu.menu_admin
                    - cmf_menu.node_admin
                    #- cmf_menu.admin
#                    - cmf_menu.multilang.admin
        #    blog:
        #        label: blog
        #        items:
        #            - cmf_blog.admin
        #            - cmf_post.admin
            simplecms:
                label: simple cms (content/routing/menu as one)
                items:
                    - cmf_simple_cms.admin.page

sonata_doctrine_phpcr_admin:
    document_tree:
        Doctrine\ODM\PHPCR\Document\Generic:
            valid_children:
                - all
        Symfony\Cmf\Bundle\ContentBundle\Document\StaticContent:
            valid_children:
                - Symfony\Cmf\Bundle\BlockBundle\Document\SimpleBlock
                - Symfony\Cmf\Bundle\BlockBundle\Document\ContainerBlock
                - Symfony\Cmf\Bundle\BlockBundle\Document\ReferenceBlock
                - Symfony\Cmf\Bundle\BlockBundle\Document\ActionBlock
        Symfony\Cmf\Bundle\BlockBundle\Document\ReferenceBlock:
            valid_children: []
        Symfony\Cmf\Bundle\BlockBundle\Document\ActionBlock:
            valid_children: []
        Symfony\Cmf\Bundle\BlockBundle\Document\SimpleBlock:
            valid_children: []
        Symfony\Cmf\Bundle\BlockBundle\Document\ContainerBlock:
            valid_children:
                - Symfony\Cmf\Bundle\BlockBundle\Document\SimpleBlock
                - Symfony\Cmf\Bundle\BlockBundle\Document\ContainerBlock
                - Symfony\Cmf\Bundle\BlockBundle\Document\ReferenceBlock
                - Symfony\Cmf\Bundle\BlockBundle\Document\ActionBlock
        Symfony\Cmf\Bundle\SimpleCmsBundle\Document\Page:
            valid_children:
                - Symfony\Cmf\Bundle\BlockBundle\Document\SimpleBlock
                - Symfony\Cmf\Bundle\BlockBundle\Document\ContainerBlock
                - Symfony\Cmf\Bundle\BlockBundle\Document\ReferenceBlock
                - Symfony\Cmf\Bundle\BlockBundle\Document\ActionBlock
        Symfony\Cmf\Bundle\SimpleCmsBundle\Document\MultilangPage:
            valid_children:
                - all
        Symfony\Cmf\Bundle\RoutingBundle\Document\Route:
            valid_children:
                - Symfony\Cmf\Bundle\RoutingBundle\Document\Route
                - Symfony\Cmf\Bundle\RoutingBundle\Document\RedirectRoute
        Symfony\Cmf\Bundle\RoutingBundle\Document\RedirectRoute:
            valid_children: []
        Symfony\Cmf\Bundle\MenuBundle\Document\MenuNode:
            valid_children:
                - Symfony\Cmf\Bundle\MenuBundle\Document\MenuNode
#        Symfony\Cmf\Bundle\BlogBundle\Document\Blog:
#            valid_children:
#                - Symfony\Cmf\Bundle\BlogBundle\Document\Post
#        Symfony\Cmf\Bundle\BlogBundle\Document\Post:
#            valid_children: []