all:
    - Symfony\Bundle\FrameworkBundle\FrameworkBundle
    - Symfony\Bundle\TwigBundle\TwigBundle
    - Symfony\Bundle\MonologBundle\MonologBundle
    - Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle
    - Symfony\Bundle\DoctrineBundle\DoctrineBundle
    - Symfony\Bundle\AsseticBundle\AsseticBundle
    - Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle
    - rs\kaoz4Bundle\rskaoz4Bundle
    - rs\kaoz4FrontBundle\rskaoz4FrontBundle
    - Knp\Bundle\MenuBundle\KnpMenuBundle
    - Knp\Bundle\LastTweetsBundle\KnpLastTweetsBundle
    - Knp\Bundle\ZendCacheBundle\KnpZendCacheBundle
    - Knp\Bundle\DisqusBundle\KnpDisqusBundle
    - JMS\AopBundle\JMSAopBundle
    - Stof\DoctrineExtensionsBundle\StofDoctrineExtensionsBundle
    - IHQS\ContactBundle\IHQSContactBundle
    - Mopa\BootstrapBundle\MopaBootstrapBundle
    - Ornicar\AkismetBundle\OrnicarAkismetBundle
    - rs\ProjectUtilitiesBundle\rsProjectUtilitiesBundle
    - FOQ\ElasticaBundle\FOQElasticaBundle
    - Knp\Bundle\PaginatorBundle\KnpPaginatorBundle
    - Blage\ConnectBundle\BlageConnectBundle

dev:
    - Symfony\Bundle\WebProfilerBundle\WebProfilerBundle
#    - Sensio\Bundle\DistributionBundle\SensioDistributionBundle
    - Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle
    - Symfony\Bundle\DoctrineFixturesBundle\DoctrineFixturesBundle
    - Elao\WebProfilerExtraBundle\WebProfilerExtraBundle

test:    
    - Behat\MinkBundle\MinkBundle
    - Behat\BehatBundle\BehatBundle
    - Symfony\Bundle\WebProfilerBundle\WebProfilerBundle
    - Elao\WebProfilerExtraBundle\WebProfilerExtraBundle
    - Symfony\Bundle\DoctrineFixturesBundle\DoctrineFixturesBundle
