# cmf configuration
doctrine_phpcr:
    # configure the PHPCR session
    session:
        backend: %phpcr_backend%
        workspace: %phpcr_workspace%
        username: %phpcr_user%
        password: %phpcr_pass%
    # enable the ODM layer
    odm:
        auto_mapping: true
        auto_generate_proxy_classes: %kernel.debug%
        locales:
            en:
                - de
            de:
                - en

cmf_core:
    persistence:
        phpcr:
            enabled: true
            use_sonata_admin: auto
            basepath: /cms
    publish_workflow:
        enabled: false
    multilang:
        locales: %locales%

cmf_blog:
    use_sonata_admin:     auto
    blog_basepath:        /cms

cmf_create:
    editor_base_path: /bundles/cmfcreate/vendor/ckeditor/

cmf_block:
    persistence:
        phpcr:
            block_basepath: /cms
    caches:
        ssi:
           token: loremipsum
cmf_routing:
    chain:
        routers_by_id:
            cmf_routing.dynamic_router: 20
            router.default: 100
    dynamic:
        enabled: true
        controllers_by_class:
            Symfony\Cmf\Bundle\BlogBundle\Document\Blog: cmf_blog.blog_controller:listAction
            Symfony\Cmf\Bundle\BlogBundle\Document\Post: cmf_blog.blog_controller:viewPostAction


cmf_simple_cms:
    persistence:
        phpcr:
            document_class: kaoz5\CmfBundle\Document\Page
    routing:
        templates_by_class:
#            Symfony\Cmf\Bundle\SimpleCmsBundle\Doctrine\Phpcr\Page:  CmfSimpleCmsBundle:Page:index.html.twig
            kaoz5\CmfBundle\Document\Page:  CmfSimpleCmsBundle:Page:index.html.twig
        controllers_by_class:
            Symfony\Cmf\Bundle\RoutingBundle\Doctrine\Phpcr\RedirectRoute:  cmf_routing.redirect_controller:redirectAction

cmf_search:
    show_paging:          true
    persistence:
        phpcr:
            enabled:              true
            search_basepath:      /cms
            search_fields:
                summary: "phpcr_locale:de-body"
                title: "phpcr_locale:title"