imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

mink:
    base_url:   http://kaoz4/app_dev.php
    default_session:    symfony

doctrine:
    dbal:
        driver: pdo_sqlite        
        path: ':memory:'
        memory: true
    
#nelmio_esi_debug:
#    enabled: false    