imports:
    - { resource: parameters.yml }
    - { resource: "@rskaoz4FrontBundle/Resources/config/services.yml" }
    - { resource: "@rskaoz4Bundle/Resources/config/services.yml" }
    - { resource: "@rskaoz4Bundle/Resources/config/config.yml" }
    - { resource: security.yml }


liip_doctrine_cache:
    namespaces:
        knp_last_tweets:
            type: file_system
            directory: %kernel.cache_dir%
        sensio_connect:
            type: file_system
            directory: %kernel.cache_dir%
        github:
            type: file_system
            directory: %kernel.cache_dir%

sensio_labs_connect:
    app_id:     40eb4a30fdba385843d351c6f54fc70c01341483a46f00a05a0d181b36353974
    app_secret: 38f28a05eb439dc22f012bb8a2adec107ce1d09f101d5fbefe33cc78a34d6e7e
    scope:      SCOPE_PUBLIC

knp_last_tweets:
    fetcher:
        driver: doctrine_cache
        options:
            cache_service: liip_doctrine_cache.ns.knp_last_tweets

knp_disqus:
    api_key: sMyTGRuFIGDwszWATZlLk0yhS0vIXjhm

ornicar_akismet:
    api_key:        %akismet_key%
    url:            http://digitalkaoz.net

blage_connect:
    profile_name: %sensio_profile%


fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        website:
            client: default
            types:
                post:
                    mappings:
                        title: { boost: 5 }
                        abstract: { boost: 3 }
                        text: { boost: 3 }
                        slug: ~
                    persistence:
                        driver: orm
                        model: rs\kaoz4Bundle\Entity\Post
                        provider:
                          query_builder_method: createIsActiveQueryBuilder

                project:
                    mappings:
                        name: { boost: 5 }
                        abstract: { boost: 3 }
                        description: { boost: 3 }
                        slug: ~
                    persistence:
                        driver: orm
                        model: rs\kaoz4Bundle\Entity\Project
                        provider:
                          query_builder_method: createIsActiveQueryBuilder
                github:
                    mappings:
                        name: { boost: 5 }
                        url:  ~
                        language: ~
                        description: { boost: 3}

k_phoen_contact:
    to:           foo@bar.baz
    redirect_url: homepage      # the url to retirect the user to once the mail
                                # is sent