imports:
    - { resource: parameters.yml }
    - { resource: cmf_config.yml }
    - { resource: backend_config.yml }
    - { resource: security.yml }
    - { resource: @CmfBlogBundle/Resources/config/routing/autoroute_default.yml }

framework:
    #esi:             ~
    translator:      { fallback: en }
    secret:          %secret%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
#    bundles:        [ kaoz5CmfBundle, kaoz5UserBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        yui_js:
             jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar
        yui_css:
             jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar
        less:
            node:       %node_path%
            node_paths: [%node_modules_path%]

# for jackalope-doctrine-dbal
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        path:     %database_path%
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

liip_doctrine_cache:
    namespaces:
        meta:
            type: file_system
        nodes:
            type: file_system

knp_menu:
    twig: true

lunetics_locale:
    strict_mode: true
    guessing_order:
        - cookie
        - router
        - browser
    allowed_locales: %locales%

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: kaoz5\UserBundle\Entity\User

fos_rest:
    view:
        formats:
            json: true

#raul_fraile_ladybug:
#    object_max_nesting_level: 10

fos_js_routing:
    routes_to_expose:
        - admin_sandbox_main_editablestaticcontent_create
        - admin_sandbox_main_editablestaticcontent_delete
        - admin_sandbox_main_editablestaticcontent_edit
        - admin_bundle_menu_menunode_create
        - admin_bundle_menu_menunode_delete
        - admin_bundle_menu_menunode_edit
        - admin_bundle_menu_multilangmenunode_create
        - admin_bundle_menu_multilangmenunode_delete
        - admin_bundle_menu_multilangmenunode_edit
        - admin_bundle_content_multilangstaticcontent_create
        - admin_bundle_content_multilangstaticcontent_delete
        - admin_bundle_content_multilangstaticcontent_edit
        - admin_bundle_content_staticcontent_create
        - admin_bundle_content_staticcontent_delete
        - admin_bundle_content_staticcontent_edit
        - admin_bundle_routingextra_route_create
        - admin_bundle_routingextra_route_delete
        - admin_bundle_routingextra_route_edit
        - admin_bundle_simplecms_page_create
        - admin_bundle_simplecms_page_delete
        - admin_bundle_simplecms_page_edit
        - cmf_tree_browser.phpcr_children
        - cmf_tree_browser.phpcr_move
        - sonata.admin.doctrine_phpcr.phpcrodm_children
        - sonata.admin.doctrine_phpcr.phpcrodm_move
        - presta_cms_page_edit
        - admin_bundle_blog_blog_create
        - admin_bundle_blog_blog_delete
        - admin_bundle_blog_blog_edit

liip_imagine:
    # ...
    filter_sets:
        #??? CreateJS ?
        image_upload_thumbnail:
            data_loader: cmf_media_doctrine_phpcr
            quality: 85
            filters:
                thumbnail: { size: [616, 419], mode: outbound }
        #???
        cmf_block:
            data_loader: cmf_media_doctrine_phpcr
            quality: 85
            filters:
                thumbnail: { size: [616, 419], mode: outbound }
        stage_block:
            data_loader: cmf_media_doctrine_phpcr
            quality: 85
            filters:
                thumbnail: { size: [850, 350], mode: inset }
        admin_list:
            data_loader: cmf_media_doctrine_phpcr
            quality: 85
            filters:
                thumbnail: { size: [50, 50], mode: inset }