digitalkaoz_github_contributions:
    resource: "@digitalkaozGithubContributionsBundle/Resources/config/routing.xml"
    prefix:   /

kaoz5_cmf:
    resource: "@kaoz5CmfBundle/Resources/config/routing.xml"
    prefix:   /

#kaoz5_user:
#    resource: "@kaoz5UserBundle/Controller/"
#    type:     annotation
#    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

#users:
#    type:     rest
#    resource: kaoz5\UserBundle\Controller\UsersRestController

home:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: /cms/simple/home
        permanent: true # this for 301

elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"

_imagine:
    resource: .
    type:     imagine

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

static:
    pattern: /{_locale}/static
    defaults:
        _controller: AcmeMainBundle:Demo:static
    requirements:
        _locale: en|de

cmf_create_rest:
    resource: "@CmfCreateBundle/Resources/config/routing/rest.xml"

cmf_create_image:
    resource: "@CmfCreateBundle/Resources/config/routing/image.xml"

admin:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

#phpcr_admin:
#    resource: "@SonataDoctrinePHPCRAdminBundle/Resources/config/routing/phpcrodmbrowser.xml"
#    prefix: /admin
#
#phpcr_admin_tree:
#    resource: "@SonataDoctrinePHPCRAdminBundle/Resources/config/routing/tree.xml"
#    prefix: /admin

sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

cmf_search:
    resource: "@CmfSearchBundle/Resources/config/routing/phpcr/search.xml"

cmf_tree:
    resource: .
    type: "cmf_tree"

cmf_media_file:
    resource: "@CmfMediaBundle/Resources/config/routing/file.xml"

cmf_media_image:
    resource: "@CmfMediaBundle/Resources/config/routing/image.xml"

block_cache:
    resource: "@CmfBlockBundle/Resources/config/routing/cache.xml"
    prefix: /