<?php

namespace rs\kaoz4Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    
    /**
     * find all networks by active
     * 
     * @return array 
     */
    public function findActive()
    {
        return $this->findBy(array(
            'active'=>true
        ));
    }    
    
    public function findLatest()
    {
        return $this
            ->createQueryBuilder('p')
            ->orderBy('p.created_at', 'ASC')
            ->setMaxResults(1)                
            ->getQuery()
            ->getSingleResult();
        
    }
    
    public function createIsActiveQueryBuilder()
    {
        return $this->createQueryBuilder('p')->where('p.active=1');
    }
}