parameters:
    kaoz4.github.fetcher.class:         rs\kaoz4Bundle\Github\ZendCacheFetcher
    kaoz4.github.fetcher.cache_name:    github
    kaoz4.github.api_client:            Github_Client
    kaoz4.search.provider.github.class: rs\kaoz4Bundle\Github\SearchProvider

services:
  
    kaoz4.menu_renderer:
        class: rs\kaoz4FrontBundle\Menu\BootstrapRenderer
        arguments: [%kernel.charset%]
        tags:
            - { name: knp_menu.renderer, alias: bootstrap }    
            
    kaoz4.menu_builder:
        class: rs\kaoz4FrontBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    kaoz4.menu.main:
        class: Knp\Menu\MenuItem
        factory_service: kaoz4.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: main }
            
    kaoz4.menu.footer:
        class: Knp\Menu\MenuItem
        factory_service: kaoz4.menu_builder
        factory_method: createFooterMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: footer }
            
    kaoz4.github.api:
        class: %kaoz4.github.api_client%

    kaoz4.github.fetcher.zend_cache:
        class: %kaoz4.github.fetcher.class%
        arguments:
            - '@kaoz4.github.api'
            - '@knp_zend_cache.manager'
            - %kaoz4.github.fetcher.cache_name%

    kaoz4.search.provider.github:
        class: %kaoz4.search.provider.github.class%
        tags:
            -  { name: foq_elastica.provider, index: website, type: github }
        arguments:
            - '@foq_elastica.index.website.github'
            - '@kaoz4.github.fetcher.zend_cache'
            - %kaoz4.github.account%