parameters:
    kaoz4.github.fetcher.class:         rs\kaoz4Bundle\Github\CacheFetcher
    kaoz4.github.api_client:            Github\Client
    kaoz4.search.provider.github.class: rs\kaoz4Bundle\Github\SearchProvider

services:
  
    kaoz4.menu_renderer:
        class: rs\kaoz4FrontBundle\Menu\BootstrapRenderer
        arguments: [%kernel.charset%]
        tags:
            - { name: knp_menu.renderer, alias: bootstrap }    
            
    kaoz4.menu_builder:
        class: rs\kaoz4FrontBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    kaoz4.menu.main:
        class: Knp\Menu\MenuItem
        factory_service: kaoz4.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: main }
            
    kaoz4.menu.footer:
        class: Knp\Menu\MenuItem
        factory_service: kaoz4.menu_builder
        factory_method: createFooterMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: footer }


    kaoz4.cached.github_client:
        class: Github\HttpClient\CachedHttpClient
        arguments: [{ cache_dir: '/tmp/github-api-cache' }]
        public: false

    kaoz4.github.api:
        class: %kaoz4.github.api_client%
        arguments:
            - '@kaoz4.cached.github_client'

    kaoz4.github.fetcher.cache:
        class: %kaoz4.github.fetcher.class%
        arguments:
            - '@kaoz4.github.api'
            - '@liip_doctrine_cache.ns.github'

    kaoz4.search.provider.github:
        class: %kaoz4.search.provider.github.class%
        tags:
            -  { name: fos_elastica.provider, index: website, type: github }
        arguments:
            - '@fos_elastica.index.website.github'
            - '@kaoz4.github.fetcher.cache'
            - %kaoz4.github.account%

    blage_connect.cache:
        class: %blage_connect.cache.class%
        arguments:
            - '@blage_connect.sensio'
            - '@liip_doctrine_cache.ns.sensio_connect'
