parameters:
    kaoz4.github.fetcher.class:      rs\kaoz4Bundle\Github\ZendCacheFetcher
    kaoz4.github.fetcher.cache_name: github
    kaoz4.github.api_client:         Github_Client
    kaoz4.search.provider.github.class:     rs\kaoz4Bundle\Github\SearchProvider

services:

    kaoz4.github.api:
        class: %kaoz4.github.api_client%

    kaoz4.github.fetcher.zend_cache:
        class: %kaoz4.github.fetcher.class%
        arguments:
            - '@kaoz4.github.api'
            - '@knp_zend_cache.manager'
            - %kaoz4.github.fetcher.cache_name%
            - %kaoz4.github.account%

    kaoz4.search.provider.github:
        class: %kaoz4.search.provider.github.class%
        tags:
            -  { name: foq_elastica.provider }
        arguments:
            - '@foq_elastica.index.website.github'
            - '@kaoz4.github.fetcher.zend_cache'
            - %kaoz4.github.account%
